package com.khrd.pingapp.utils.passwordValidation

enum class ValidationState() {
    VALID,
    NAME_IS_BLANK,
    NAME_LETTERS_FAILURE,
    NAME_LENGTH_FAILURE,
    EMAIL_IS_BLANK,
    EMAIL_IS_INVALID,
    PASSWORD_IS_BLANK,
    PASSWORD_IS_SHORT,
    PASSWORD_IS_LONG,
    PASSWORD_WITHOUT_DIGIT,
    PASSWORD_WITHOUT_UPPER_LETTER,
    PASSWORD_WITHOUT_LOWER_LETTER,
    PASSWORDS_ARE_SAME,
    CONSENT_NOT_GIVEN
}